name: recipeapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
assets:
  images/
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore_web: ^3.8.10
  firebase_auth_web: ^5.8.12
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.4.0
  fluro: ^2.0.3



dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
